//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MokitShop.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportProduct
    {
        public int Id { get; set; }
        public System.DateTime DateImport { get; set; }
        public int ProId { get; set; }
        public int Quantity { get; set; }
        public int StaffId { get; set; }
        public string Description { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
