//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MokitShop.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Carts = new HashSet<Cart>();
            this.ImportProducts = new HashSet<ImportProduct>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Product_Sales = new HashSet<Product_Sales>();
        }
    
        public int ProId { get; set; }
        public string ProName { get; set; }
        public int ManufacturerId { get; set; }
        public int ScaleId { get; set; }
        public int SerialId { get; set; }
        public int OriginalId { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public decimal Price { get; set; }
        public int PointAcquired { get; set; }
        public string ProCode { get; set; }
        public string Description { get; set; }
        public string ImagePath { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int Quantity { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportProduct> ImportProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Sales> Product_Sales { get; set; }
        public virtual ProductProperty ProductProperty { get; set; }
        public virtual ProductProperty ProductProperty1 { get; set; }
        public virtual ProductProperty ProductProperty2 { get; set; }
        public virtual ProductProperty ProductProperty3 { get; set; }
    }
}
